// <auto-generated />
using CLE_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CLE_BackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260411184935_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CLE_BackEnd.Models.Company", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CCEmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("CLEKmailNotification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("text");

                    b.Property<string>("HandphoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PICName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SSMNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SSTNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanyCode");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyCode = "A0001",
                            Address = "Butterworth, 13000, Penang",
                            CCEmailAddress = "finance@gmail.com.my",
                            CLEKmailNotification = "operater@gmail.com",
                            CompanyName = "ABC Forwarders",
                            EmailAddress = "nesh@gmail.com.my",
                            FaxNumber = "03-12345679",
                            HandphoneNumber = "012-3456789",
                            ManagerName = "Pradeep",
                            PICName = "Thanesh",
                            Region = "PNG",
                            Role = "Forwarder",
                            SSMNo = "123456-A",
                            SSTNo = "W10-1234-5678",
                            TelephoneNumber = "03-12345678"
                        },
                        new
                        {
                            CompanyCode = "A0002",
                            Address = "Port Klang, 57000, Penang",
                            CCEmailAddress = "finance@hotmail.com.my",
                            CLEKmailNotification = "operater@hotmail.com",
                            CompanyName = "ABC Haulier",
                            EmailAddress = "lee@hotmail.com.my",
                            FaxNumber = "03-12345679",
                            HandphoneNumber = "012-3456789",
                            ManagerName = "Tristen",
                            PICName = "Lee Jia Jun",
                            Region = "PKG",
                            Role = "Haulier",
                            SSMNo = "123456-B",
                            SSTNo = "W11-1234-5678",
                            TelephoneNumber = "03-12345678"
                        });
                });

            modelBuilder.Entity("CLE_BackEnd.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyCode");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "MNG00001",
                            Access = "CLE & ALE",
                            AccessLevel = "Full-Access",
                            CompanyCode = "A0001",
                            CompanyName = "ABC Forwarders",
                            ContactNumber = "0123456789",
                            EmailAddress = "deep@gmail.com",
                            FullName = "Pradeep",
                            Password = "123456",
                            Status = "Active",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            UserId = "STF00001",
                            Access = "CLE",
                            AccessLevel = "Half-Access",
                            CompanyCode = "A0001",
                            CompanyName = "ABC Forwarders",
                            ContactNumber = "0123456789",
                            EmailAddress = "nesh@gmail.com",
                            FullName = "Thanesh",
                            Password = "123456",
                            Status = "Active",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            UserId = "MNG00002",
                            Access = "CLE & ALE",
                            AccessLevel = "Full-Access",
                            CompanyCode = "A0002",
                            CompanyName = "ABC Haulier",
                            ContactNumber = "0123456789",
                            EmailAddress = "tristen@hotmail.com",
                            FullName = "Tristen",
                            Password = "123456",
                            Status = "Active",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            UserId = "STF0002",
                            Access = "ALE",
                            AccessLevel = "Full-Access",
                            CompanyCode = "A0002",
                            CompanyName = "ABC Haulier",
                            ContactNumber = "0123456789",
                            EmailAddress = "vincent@hotmail.com",
                            FullName = "Vincent",
                            Password = "123456",
                            Status = "Active",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CLE_BackEnd.Models.User", b =>
                {
                    b.HasOne("CLE_BackEnd.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
