// <auto-generated />
using System;
using CLE_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CLE_BackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CLE_BackEnd.Models.AssignedHaulier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerId")
                        .HasColumnType("integer");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HaulierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PMNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ROTNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("ROTNumber");

                    b.ToTable("AssignedHauliers");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.Booking", b =>
                {
                    b.Property<string>("ROTNumber")
                        .HasColumnType("text");

                    b.Property<string>("BLOrBookingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingParty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContainerQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("CustomFormNo")
                        .HasColumnType("text");

                    b.Property<string>("CustomReceiptNo")
                        .HasColumnType("text");

                    b.Property<string>("DICNumber")
                        .HasColumnType("text");

                    b.Property<string>("DepotRemarks")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ETA")
                        .HasColumnType("date");

                    b.Property<string>("ForwardingId")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("ForwardingRemarks")
                        .HasColumnType("text");

                    b.Property<string>("HaulierRemarks")
                        .HasColumnType("text");

                    b.Property<string>("HouseBLNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortLocation")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("SCN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SealNumber")
                        .HasColumnType("text");

                    b.Property<string>("ShippingAgentId")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("TripType")
                        .HasColumnType("text");

                    b.Property<string>("ZBNumber")
                        .HasColumnType("text");

                    b.HasKey("ROTNumber");

                    b.HasIndex("ForwardingId");

                    b.HasIndex("PortLocation");

                    b.HasIndex("ShippingAgentId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.BookingDocument", b =>
                {
                    b.Property<Guid>("BookingDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ROTNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookingDocumentId");

                    b.HasIndex("ROTNumber");

                    b.ToTable("BookingDocuments");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.Company", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CCEmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("CLEKmailNotification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("text");

                    b.Property<string>("HandphoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PICName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SSMNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SSTNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanyCode");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyCode = "A0001",
                            Address = "Butterworth, 13000, Penang",
                            CCEmailAddress = "finance@gmail.com.my",
                            CLEKmailNotification = "operater@gmail.com",
                            CompanyName = "ABC Forwarders",
                            EmailAddress = "nesh@gmail.com.my",
                            FaxNumber = "03-12345679",
                            HandphoneNumber = "012-3456789",
                            LogoPath = "",
                            ManagerName = "Pradeep",
                            PICName = "Thanesh",
                            Region = "PNG",
                            Role = "Forwarder",
                            SSMNo = "123456-A",
                            SSTNo = "W10-1234-5678",
                            TelephoneNumber = "03-12345678"
                        },
                        new
                        {
                            CompanyCode = "A0002",
                            Address = "Port Klang, 57000, Penang",
                            CCEmailAddress = "finance@hotmail.com.my",
                            CLEKmailNotification = "operater@hotmail.com",
                            CompanyName = "ABC Haulier",
                            EmailAddress = "lee@hotmail.com.my",
                            FaxNumber = "03-12345679",
                            HandphoneNumber = "012-3456789",
                            LogoPath = "",
                            ManagerName = "Tristen",
                            PICName = "Lee Jia Jun",
                            Region = "PKG",
                            Role = "Haulier",
                            SSMNo = "123456-B",
                            SSTNo = "W11-1234-5678",
                            TelephoneNumber = "03-12345678"
                        });
                });

            modelBuilder.Entity("CLE_BackEnd.Models.Container", b =>
                {
                    b.Property<int>("ContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContainerId"));

                    b.Property<DateTime>("AssignedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsigneeId")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("ContainerNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContainerSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("DGCRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("DGCReduction")
                        .HasColumnType("double precision");

                    b.Property<bool>("DGCReductionEligibility")
                        .HasColumnType("boolean");

                    b.Property<string>("DeletedRemarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepotId")
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime?>("EnrouteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GatedInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GatedOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HaulierId")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("PortId")
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime?>("RFCTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ROTDate")
                        .HasColumnType("date");

                    b.Property<string>("ROTNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RTAssignedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RTDeliveredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RTEnrouteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RTGatedInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RTGatedOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RTRFCTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RejectedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TimeStatus")
                        .HasColumnType("text");

                    b.Property<string>("TrailerType")
                        .HasColumnType("text");

                    b.Property<int?>("TurnAroundTime")
                        .HasColumnType("integer");

                    b.Property<string>("VGM")
                        .HasColumnType("text");

                    b.HasKey("ContainerId");

                    b.HasIndex("ConsigneeId");

                    b.HasIndex("DepotId");

                    b.HasIndex("HaulierId");

                    b.HasIndex("PortId");

                    b.HasIndex("ROTNumber");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.ContainerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContainerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("ContainerAddresses");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyCode");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "MNG00001",
                            Access = "CLE & ALE",
                            AccessLevel = "Full-Access",
                            CompanyCode = "A0001",
                            CompanyName = "ABC Forwarders",
                            ContactNumber = "0123456789",
                            EmailAddress = "deep@gmail.com",
                            FullName = "Pradeep",
                            Password = "123456",
                            Status = "Active",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            UserId = "STF00001",
                            Access = "CLE",
                            AccessLevel = "Half-Access",
                            CompanyCode = "A0001",
                            CompanyName = "ABC Forwarders",
                            ContactNumber = "0123456789",
                            EmailAddress = "nesh@gmail.com",
                            FullName = "Thanesh",
                            Password = "123456",
                            Status = "Active",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            UserId = "MNG00002",
                            Access = "CLE & ALE",
                            AccessLevel = "Full-Access",
                            CompanyCode = "A0002",
                            CompanyName = "ABC Haulier",
                            ContactNumber = "0123456789",
                            EmailAddress = "tristen@hotmail.com",
                            FullName = "Tristen",
                            Password = "123456",
                            Status = "Active",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            UserId = "STF0002",
                            Access = "ALE",
                            AccessLevel = "Full-Access",
                            CompanyCode = "A0002",
                            CompanyName = "ABC Haulier",
                            ContactNumber = "0123456789",
                            EmailAddress = "vincent@hotmail.com",
                            FullName = "Vincent",
                            Password = "123456",
                            Status = "Active",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CLE_BackEnd.Models.AssignedHaulier", b =>
                {
                    b.HasOne("CLE_BackEnd.Models.Container", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLE_BackEnd.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("ROTNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Container");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.Booking", b =>
                {
                    b.HasOne("CLE_BackEnd.Models.Company", "ForwardingCompany")
                        .WithMany()
                        .HasForeignKey("ForwardingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLE_BackEnd.Models.Company", "PortLocationCompany")
                        .WithMany()
                        .HasForeignKey("PortLocation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLE_BackEnd.Models.Company", "ShippingAgentCompany")
                        .WithMany()
                        .HasForeignKey("ShippingAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ForwardingCompany");

                    b.Navigation("PortLocationCompany");

                    b.Navigation("ShippingAgentCompany");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.BookingDocument", b =>
                {
                    b.HasOne("CLE_BackEnd.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("ROTNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.Container", b =>
                {
                    b.HasOne("CLE_BackEnd.Models.Company", "ConsigneeCompany")
                        .WithMany()
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLE_BackEnd.Models.Company", "DepotCompany")
                        .WithMany()
                        .HasForeignKey("DepotId");

                    b.HasOne("CLE_BackEnd.Models.Company", "HaulierCompany")
                        .WithMany()
                        .HasForeignKey("HaulierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CLE_BackEnd.Models.Company", "PortCompany")
                        .WithMany()
                        .HasForeignKey("PortId");

                    b.HasOne("CLE_BackEnd.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("ROTNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ConsigneeCompany");

                    b.Navigation("DepotCompany");

                    b.Navigation("HaulierCompany");

                    b.Navigation("PortCompany");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.ContainerAddress", b =>
                {
                    b.HasOne("CLE_BackEnd.Models.Container", "Container")
                        .WithMany("ToAddress")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.User", b =>
                {
                    b.HasOne("CLE_BackEnd.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CLE_BackEnd.Models.Container", b =>
                {
                    b.Navigation("ToAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
